######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 10 19:09:53 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/z/t/ztc/Documents/EC535/lab5/qt/. .

# Input
SOURCES += main.cpp
